server:
  port: 8070

springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger.html
  api-docs:
    path : /api-docs

# H2
spring:
  jpa:
    open-in-view: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: game-crud
  # Datasource
  datasource:
    url: jdbc:h2:file:/data/demo
    username: admin
    password: ''
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: '/h2'
#logger
logging:
  level:
    root: WARN
    com.assignment: INFO
  file:
    name: './game-cred-dev.log'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%'